import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Eye, EyeOff } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useBrand } from '../../context/BrandContext';
import { Logo } from '../../components/ui/Logo';
export function LoginPage() {
 const {branding,isSchoolPortal}=useBrand(); const {login,user}=useAuth(); const navigate=useNavigate();
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [visible,setVisible]=useState(false); const [busy,setBusy]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{if(submitted&&user)navigate(user.role==='superadmin'?'/admin-panel':user.role==='teacher'?'/teacher-portal':user.role==='student'?'/student-portal':'/dashboard',{replace:true});},[submitted,user,navigate]);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const result=await login(email.trim(),password);if(result.success)setSubmitted(true);else setError(result.error||'Sign-in failed.');}catch{setError('Unable to sign in. Please retry.');}finally{setBusy(false);}};
 return <main className="min-h-screen flex items-center justify-center p-4 sm:p-8" style={{background:'linear-gradient(145deg,var(--brand-secondary),var(--brand-primary))'}}><div className="w-full max-w-md bg-white text-slate-900 rounded-3xl shadow-xl p-7 sm:p-10"><header className="text-center flex flex-col items-center"><Logo variant="icon" size={80}/><h1 className="font-bold text-2xl mt-6">{branding.portalTitle||branding.schoolName}</h1><p className="text-slate-600 text-sm mt-3">{isSchoolPortal?'Sign in to your school account.':'Sign in to GlobePen.'}</p>{isSchoolPortal&&branding.slogan&&<p className="text-sm text-slate-500 mt-2">{branding.slogan}</p>}</header>
 <form onSubmit={submit} className="mt-8 space-y-5"><label className="grid gap-2 font-medium" htmlFor="login-email">Email address<input id="login-email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} className="border border-slate-300 rounded-xl p-3"/></label><label className="grid gap-2 font-medium" htmlFor="login-password">Password<div className="relative"><input id="login-password" type={visible?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="border border-slate-300 rounded-xl p-3 pr-12 w-full"/><button type="button" aria-label={visible?'Hide password':'Show password'} className="absolute right-3 top-3" onClick={()=>setVisible(!visible)}>{visible?<EyeOff/>:<Eye/>}</button></div></label><Link className="block text-sm underline text-slate-600" to="/forgot-password">Forgot password?</Link>{error&&<p role="alert" className="text-red-700 bg-red-50 rounded-lg p-3">{error}</p>}<button disabled={busy} className="w-full rounded-xl p-4 font-bold disabled:opacity-60" style={{backgroundColor:'var(--brand-primary)',color:'var(--brand-on-primary)'}}>{busy?'Signing in…':'Sign In'}</button></form>
 <footer className="text-center text-sm text-slate-500 mt-7"><Link to="/" className="underline">Back to {isSchoolPortal?'school website':'GlobePen'}</Link>{branding.contactEmail&&<p className="mt-4">Support: <a className="underline break-all" href={`mailto:${branding.contactEmail}`}>{branding.contactEmail}</a></p>}{isSchoolPortal&&<p className="text-xs mt-6">Powered by GlobePen</p>}</footer></div></main>;
}
