import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Eye, EyeOff, AlertCircle } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import { useBrand } from '../../context/BrandContext';
import { Logo } from '../../components/ui/Logo';
export function LoginPage() {
 const {branding,isSchoolPortal}=useBrand(); const {login,user}=useAuth(); const navigate=useNavigate();
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [visible,setVisible]=useState(false); const [busy,setBusy]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{if(submitted&&user)navigate(user.role==='superadmin'?'/admin-panel':user.role==='teacher'?'/teacher-portal':user.role==='student'?'/student-portal':'/dashboard',{replace:true});},[submitted,user,navigate]);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const result=await login(email.trim(),password);if(result.success)setSubmitted(true);else setError(result.error||'Sign-in failed.');}catch{setError('Unable to sign in. Please retry.');}finally{setBusy(false);}};
 return <main className="min-h-screen flex items-center justify-center p-4 sm:p-8" aria-labelledby="login-title" style={{background:'linear-gradient(145deg,var(--brand-secondary),var(--brand-primary))'}}><div className="w-full max-w-md bg-[var(--app-surface)] text-[var(--app-text)] rounded-3xl shadow-[var(--shadow-modal)] p-7 sm:p-10"><header className="text-center flex flex-col items-center"><Logo variant="icon" size={80}/><h1 id="login-title" className="font-bold text-2xl mt-6">{branding.portalTitle||branding.schoolName}</h1><p className="text-[var(--app-text-muted)] text-sm mt-3">{isSchoolPortal?'Sign in to your school account.':'Sign in to GlobePen.'}</p>{isSchoolPortal&&branding.slogan&&<p className="text-sm text-[var(--app-text-subtle)] mt-2">{branding.slogan}</p>}</header>
 <form onSubmit={submit} aria-busy={busy} className="mt-8 space-y-5"><label className="grid gap-2 font-semibold" htmlFor="login-email">Email address<input id="login-email" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)} className="h-11 w-full rounded-xl border border-slate-300 bg-white px-3.5 text-sm text-slate-900 placeholder:text-slate-400 shadow-sm transition-colors hover:border-slate-400 focus:border-slate-500"/></label><label className="grid gap-2 font-semibold" htmlFor="login-password">Password<div className="relative"><input id="login-password" type={visible?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="h-11 w-full rounded-xl border border-slate-300 bg-white px-3.5 pr-12 text-sm text-slate-900 placeholder:text-slate-400 shadow-sm transition-colors hover:border-slate-400 focus:border-slate-500"/><button type="button" aria-label={visible?'Hide password':'Show password'} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 rounded-lg text-slate-500 hover:bg-slate-100 hover:text-slate-700" onClick={()=>setVisible(!visible)}>{visible?<EyeOff className="w-5 h-5"/>:<Eye className="w-5 h-5"/>}</button></div></label><Link className="block text-sm underline-offset-2 text-[var(--app-text-muted)] hover:text-[var(--app-text)]" to="/forgot-password">Forgot password?</Link>{error&&<p role="alert" className="flex items-start gap-2 rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm font-medium text-rose-900 dark:text-rose-100"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true"/><span>{error}</span></p>}<button disabled={busy} className="h-12 w-full rounded-xl font-bold disabled:opacity-60" style={{backgroundColor:'var(--brand-primary)',color:'var(--brand-on-primary)'}}>{busy?'Signing in…':'Sign In'}</button></form>
 <footer className="text-center text-sm text-[var(--app-text-subtle)] mt-7"><Link to="/" className="underline underline-offset-2">Back to {isSchoolPortal?'school website':'GlobePen'}</Link>{branding.contactEmail&&<p className="mt-4">Support: <a className="underline underline-offset-2 break-all" href={`mailto:${branding.contactEmail}`}>{branding.contactEmail}</a></p>}{isSchoolPortal&&<p className="text-xs mt-6">Powered by GlobePen</p>}</footer></div></main>;
}
