import React, { useEffect, useState } from 'react';
import { Link, Navigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useBrand } from '../context/BrandContext';
import api from '../lib/api';
export const DashboardPage = () => {
 const { user }=useAuth(); const { branding }=useBrand();
 const [counts,setCounts]=useState<{students:number;teachers:number;classes:number}|null>(null);
 const [error,setError]=useState(false);
 useEffect(()=>{ if(user?.role!=='admin') return; const controller=new AbortController(); setCounts(null); setError(false); api.get('/registry',{signal:controller.signal}).then(({data})=>{ if(data.schoolId!==user.schoolId) throw new Error('Tenant mismatch'); setCounts({students:data.students.length,teachers:data.teachers.length,classes:data.classes.length}); }).catch(()=>{if(!controller.signal.aborted)setError(true);}); return ()=>controller.abort(); },[user?.schoolId,user?.role]);
 if(user?.role==='teacher')return <Navigate to="/teacher-portal" replace/>;
 if(user?.role==='student')return <Navigate to="/student-portal" replace/>;
 return <main className="max-w-6xl mx-auto p-6 md:p-10 space-y-8"><header><p className="font-semibold mb-3" style={{ color: 'var(--brand-primary, #2563EB)' }}>School workspace</p><h1 className="text-3xl md:text-4xl font-bold">{branding.portalTitle || branding.schoolName}</h1><p className="mt-3 text-gray-600">Welcome, {user?.fullName}. Your school registry is ready.</p></header>{error?<p role="alert">School totals could not be loaded. Please reload.</p>:<div className="grid sm:grid-cols-3 gap-5">{(['students','teachers','classes'] as const).map(key=><Link key={key} to="/registry" className="rounded-2xl border p-6 bg-white text-gray-900"><p className="capitalize text-gray-600">{key}</p><p className="text-4xl font-bold mt-3">{counts?counts[key]:'…'}</p><p className="text-sm text-gray-500 mt-3">Saved school records</p></Link>)}</div>}<section className="rounded-2xl text-white p-8" style={{ backgroundColor: 'var(--brand-secondary, #0f172a)' }}><h2 className="text-2xl font-bold">Manage your school registry</h2><p className="opacity-90 mt-3 max-w-2xl">Add classes, students and teacher records. Changes are saved to the school account and available across signed-in devices.</p><Link to="/registry" className="inline-block rounded-lg px-6 py-3 mt-6 font-bold" style={{ backgroundColor: 'var(--brand-primary, #2563EB)', color: 'var(--brand-on-primary, #ffffff)' }}>Open School Registry</Link></section><section className="grid sm:grid-cols-2 gap-5"><Link className="border rounded-xl p-6" to="/settings"><h2 className="font-bold text-xl">School settings</h2><p className="mt-2 text-gray-600">Update the school identity and portal branding.</p></Link><Link className="border rounded-xl p-6" to="/manual"><h2 className="font-bold text-xl">School guide</h2><p className="mt-2 text-gray-600">Explore the available tools.</p></Link></section><p className="text-sm text-gray-600">Pilot note: the older academic screens retain browser-local storage. Use School Registry for shared class, teacher and student records. Email activation and recovery remain disabled.</p></main>;
};
