import React, { useState } from 'react';
import { BookOpen, GraduationCap, Gem, Laptop, Menu, Music, X } from 'lucide-react';
import type { PublicBranding } from '../../server/src/contracts/branding';
// Fallback identity used only when the school has not saved its own branding.
const FALLBACK_LOGO = 'https://ik.imagekit.io/devickys/Picsart_25-06-20_11-35-07-065.png?updatedAt=1751896002798';
const admissions = 'https://docs.google.com/forms/d/e/1FAIpQLSePWVd0Ei9m5ogrCu8tyI4u2lRA2S0HaF1dk79nPxhfdyBBfg/viewform?usp=dialog';
const nav = [['home','Home'],['about','About'],['programs','Programs'],['facilities','Facilities'],['contact','Contact']];
const programs = [
 ['Early Years','Ages 3–6 · Play-based learning focused on creativity and curiosity.',['Multi-sensory exploration','Early literacy & numeracy','Social-emotional development']],
 ['Elementary','BASIC 1–5 · Foundation building with project-based learning.',['Integrated curriculum','STEM enrichment','Character development']],
 ['Middle School','JSS 1–3 · Developing analytical thinking and self-discovery.',['Advanced mathematics','Science exploration','Electives & clubs']],
 ['High School','SS1–SS3 · Preparing students for university and beyond.',['College preparatory courses','Career counseling','Leadership programs']],
] as const;
const button='inline-flex justify-center items-center rounded-full px-6 py-3 font-bold bg-red-600 text-white hover:bg-yellow-300 hover:text-black transition-colors';
// Adapted from the original school HTML supplied by the user; no third-party form scripts.
export const DevikysLandingPage = ({branding}:{branding:PublicBranding}) => {
 const [open,setOpen]=useState(false);
 // School-saved branding wins; the fallbacks keep the page correct before branding is saved.
 const schoolName = branding.schoolName?.trim() || 'DEVICKYS GEM SCHOOL';
 const motto = branding.slogan?.trim() || 'Be of a Strong Will and Intellect';
 const logoUrl = branding.logoUrl?.trim() || FALLBACK_LOGO;
 const contactEmail = branding.contactEmail?.trim() || 'devickyscollege@gmail.com';
 return <div className="bg-black text-white min-h-screen">
 <header className="sticky top-0 z-40 bg-black/95 border-b border-yellow-300/20"><div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between gap-4">
 <a href="#home" className="flex items-center gap-3 min-w-0"><img src={logoUrl} width="48" height="48" alt={`${schoolName} logo`} className="rounded-lg"/><span className="font-black text-base lg:text-xl">{schoolName}</span></a>
 <nav aria-label="Main navigation" className="hidden xl:flex items-center gap-6">{nav.map(([id,label])=><a key={id} href={`#${id}`} className="hover:text-yellow-300">{label}</a>)}</nav>
 <div className="flex items-center gap-2"><a href="/login" className="rounded-full bg-yellow-300 text-black px-4 py-3 font-bold whitespace-nowrap text-sm">School Portal</a><button aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="school-navigation" className="xl:hidden p-2" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>
 {open&&<nav id="school-navigation" aria-label="Mobile navigation" className="xl:hidden px-6 pb-5 grid gap-4">{nav.map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{label}</a>)}</nav>}</header>
 <main><section id="home" className="scroll-mt-24 min-h-[75vh] flex items-center bg-cover bg-center" style={{backgroundImage:`linear-gradient(100deg,rgba(0,0,0,.92),rgba(0,0,0,.65)),url('${logoUrl}')`}}><div className="max-w-7xl w-full mx-auto px-6 py-24">
 <p className="inline-block rounded-full bg-red-600 px-4 py-2 text-sm font-bold mb-7">{motto}</p>
 <h1 className="font-black text-4xl md:text-6xl lg:text-7xl leading-tight max-w-5xl"><span className="text-[#FFF44F]">EXCELLENCE</span> IN EDUCATION<br/><span className="text-yellow-300">SHINING</span> THE WAY FORWARD</h1>
 <p className="text-lg md:text-xl text-gray-200 max-w-2xl mt-8 leading-relaxed">At {schoolName}, we are committed to nurturing every child's unique talents, fostering academic excellence, and developing well-rounded citizens ready to make a positive impact on the world.</p>
 <div className="flex flex-wrap gap-4 mt-10"><a href={admissions} className={button}>Apply Today</a><a href="/login" className="rounded-full border-2 border-yellow-300 text-yellow-300 px-6 py-3 font-bold hover:bg-yellow-300 hover:text-black">Enter School Portal</a></div></div></section>
 <section id="about" className="scroll-mt-24 max-w-7xl mx-auto px-6 py-20"><p className="text-yellow-300 uppercase tracking-widest text-sm mb-4">Why choose our school</p><h2 className="text-3xl md:text-5xl font-black mb-8">Our Vision & Mission</h2><p className="text-lg text-gray-300 leading-relaxed max-w-4xl">Founded in 2010, {schoolName} envisions a world where every child discovers their unique brilliance. Our mission is to provide exceptional education that ignites curiosity, fosters creativity, and develops leaders for tomorrow.</p><div className="grid md:grid-cols-2 gap-6 mt-10">{[['World-Class Faculty','Highly qualified educators with international experience'],['Holistic Development','Balancing academics, arts, sports, and values education']].map(([title,desc])=><article key={title} className="border border-yellow-300/30 bg-gray-900 rounded-2xl p-7"><Gem className="text-yellow-300 mb-5"/><h3 className="text-xl font-bold text-yellow-200 mb-3">{title}</h3><p className="text-gray-300">{desc}</p></article>)}</div></section>
 <section id="programs" className="scroll-mt-24 bg-gray-950 px-6 py-20"><div className="max-w-7xl mx-auto"><h2 className="text-3xl md:text-5xl font-black text-[#FFF44F] mb-6">Our Academic Programs</h2><p className="text-gray-300 text-lg max-w-3xl mb-12">Comprehensive academic programs designed to meet each child's developmental needs and challenge their growing minds.</p><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{programs.map(([title,desc,items])=><article key={title} className="rounded-2xl border border-yellow-300/40 bg-gray-900 p-6"><GraduationCap className="text-yellow-300 mb-6" size={36}/><h3 className="text-xl font-bold text-yellow-300 mb-4">{title}</h3><p className="text-gray-300 mb-6">{desc}</p><ul className="space-y-3">{items.map(item=><li key={item}>✓ {item}</li>)}</ul><a href="#contact" className="inline-block text-yellow-300 underline mt-6">Enquire about this program</a></article>)}</div><h3 className="text-2xl font-bold mt-16 mb-7">Our Specialized Programs</h3><div className="grid md:grid-cols-3 gap-6">{[['GEM JET Academy','Science, Technology, Engineering, Arts and Mathematics through innovation projects and competitions.'],['Creative Arts Conservatory','Visual arts, theater, music and dance.'],['Sports Excellence','Developing athletic potential through specialized coaching.']].map(([title,desc])=><article key={title} className="p-6 rounded-2xl border border-gray-700"><h4 className="font-bold text-yellow-300 text-xl mb-3">{title}</h4><p className="text-gray-300">{desc}</p></article>)}</div></div></section>
 <section id="facilities" className="scroll-mt-24 max-w-7xl mx-auto px-6 py-20"><h2 className="font-black text-3xl md:text-5xl mb-12 text-[#FFF44F]">Our Facilities</h2><div className="grid md:grid-cols-3 gap-8">{[{icon:Laptop,title:'Smart Classrooms',text:'Classrooms with interactive boards, digital resources and internet access to enhance learning.'},{icon:BookOpen,title:'Resource Library',text:'Books and digital resources with quiet study spaces to cultivate a love for reading.'},{icon:Music,title:'Performing Arts Theater',text:'An auditorium for performances and assemblies.'}].map(({icon:Icon,title,text})=><article key={title}><Icon className="text-yellow-300 mb-5" size={36}/><h3 className="text-xl font-bold mb-3">{title}</h3><p className="text-gray-300">{text}</p></article>)}</div></section>
 <section className="px-6 py-12"><div className="max-w-5xl mx-auto rounded-3xl border-2 border-yellow-300 bg-gray-950 p-8 md:p-16 text-center"><h2 className="font-bold text-3xl mb-6">Ready to Enroll Your Child?</h2><p className="text-gray-300 text-lg mb-8">Join our community of learners and discover the GEM difference today.</p><a className={button} href={admissions}>Start Your Application</a></div></section>
 <section id="contact" className="scroll-mt-24 max-w-7xl mx-auto px-6 py-20"><h2 className="text-3xl md:text-5xl font-black text-[#FFF44F] mb-10">Get In Touch</h2><div className="grid md:grid-cols-2 gap-12"><div><p className="text-lg text-gray-300 mb-7">Reach out to schedule a visit, ask questions, or begin the enrollment process.</p><h3 className="text-yellow-300 font-bold mb-3">Address</h3><p>2b, Omotola Street, Iwaya<br/>Sabo Yaba, Lagos, Nigeria</p><h3 className="text-yellow-300 font-bold mt-6 mb-3">Email</h3><a className="underline break-all" href={`mailto:${contactEmail}`}>{contactEmail}</a></div><div className="rounded-2xl bg-gray-900 p-8"><h3 className="text-xl font-bold mb-4">Contact the school</h3><p className="text-gray-300 mb-6">Send your enquiry by email, or use the admissions form to apply. Your email application will open when you choose the link below.</p><a className={button} href={`mailto:${contactEmail}`}>Write an Email</a><a className="block underline text-yellow-300 mt-6" href="https://www.facebook.com/share/172cMiWSUC/">Find us on Facebook</a></div></div></section></main>
 <footer className="border-t border-gray-800 px-6 py-10 text-center text-gray-400"><p>© {new Date().getFullYear()} {schoolName} · {motto}</p><p className="text-sm mt-3">Powered by <a className="underline" href="https://app.ifyspace.tech/">GlobePen</a></p></footer></div>;
};
